import Data.Word
import Data.Bits
main = print var_a
sigand, sigor :: Word16 -> Word16 -> Word16
sigand    = (.&.)
sigor     = (.|.)
siglshift, sigrshift :: Word16 -> Int -> Word16
siglshift = shiftL
sigrshift = shiftR
signot :: Word16 -> Word16
signot    = complement
var_ai = sigand var_af var_ah
var_ll = signot var_lk
var_is = sigrshift var_hz 1
var_gp = signot var_go
var_dv = sigor var_du var_dt
var_aa = sigrshift var_x 5
var_ba = sigor var_at var_az
var_es = siglshift var_eo 15
var_cu = sigor var_ci var_ct
var_f = sigrshift var_b 5
var_fo = sigor var_fm var_fn
var_ah = signot var_ag
var_x = sigor var_v var_w
var_j = sigand var_g var_i
var_ar = siglshift var_an 15
var_cy = sigand 1 var_cx
var_jy = sigand var_jq var_jw
var_ix = sigrshift var_iu 5
var_go = sigand var_gl var_gm
var_bx = signot var_bw
var_jr = sigrshift var_jp 3
var_hj = sigand var_hg var_hh
var_by = sigand var_bv var_bx
var_et = sigor var_er var_es
var_ks = sigor var_kl var_kr
var_fm = sigrshift var_et 1
var_h = sigand var_e var_f
var_ao = siglshift var_u 1
var_hx = sigrshift var_he 1
var_ej = sigand var_eg var_ei
var_bw = sigand var_bo var_bu
var_eg = sigor var_dz var_ef
var_ea = sigrshift var_dy 3
var_gn = sigor var_gl var_gm
var_du = siglshift var_da 1
var_aw = sigor var_au var_av
var_gv = sigor var_gj var_gu
var_fb = sigor var_eu var_fa
var_ln = sigor var_lg var_lm
var_g = sigor var_e var_f
var_dn = signot var_dm
var_m = signot var_l
var_as = sigor var_aq var_ar
var_gm = sigrshift var_gj 5
var_hp = sigand var_hm var_ho
var_gi = siglshift var_ge 15
var_ki = sigrshift var_jp 1
var_hi = sigor var_hg var_hh
var_lw = siglshift var_lc 1
var_ko = sigor var_km var_kn
var_fk = siglshift var_eq 1
var_an = sigand 1 var_am
var_hc = sigrshift var_gj 1
var_am = sigand var_aj var_al
var_gw = sigand var_gj var_gu
var_kr = sigand var_ko var_kq
var_hb = sigor var_ha var_gz
var_bz = sigor var_bn var_by
var_jc = sigor var_iv var_jb
var_ad = signot var_ac
var_bv = sigor var_bo var_bu
var_l = sigand var_d var_j
var_ce = siglshift var_bk 1
var_dl = sigor var_de var_dk
var_dw = sigrshift var_dd 1
var_im = sigand var_hz var_ik
var_je = signot var_jd
var_fp = sigrshift var_fo 2
var_hv = siglshift var_hb 1
var_lg = sigrshift var_lf 2
var_gl = sigrshift var_gj 3
var_kk = sigor var_ki var_kj
var_al = signot var_ak
var_lf = sigor var_ld var_le
var_ck = sigrshift var_ci 3
var_cd = sigand 1 var_cc
var_ky = signot var_kx
var_fw = sigor var_fp var_fv
var_ey = sigand var_ev var_ew
var_dx = siglshift var_dt 15
var_ay = signot var_ax
var_bs = sigand var_bp var_bq
var_ij = signot var_ii
var_cv = sigand var_ci var_ct
var_ir = sigor var_iq var_ip
var_y = sigrshift var_x 2
var_fs = sigor var_fq var_fr
var_bq = sigrshift var_bn 5
var_c = 0
var_b = 14146
var_k = sigor var_d var_j
var_ab = sigor var_z var_aa
var_gg = sigor var_gf var_ge
var_dh = sigor var_df var_dg
var_hk = signot var_hj
var_dj = signot var_di
var_fn = siglshift var_fj 15
var_ly = sigrshift var_lf 1
var_p = sigand var_b var_n
var_jx = sigor var_jq var_jw
var_gq = sigand var_gn var_gp
var_aq = sigrshift var_x 1
var_fa = sigand var_ex var_ez
var_fd = signot var_fc
var_bk = sigor var_bj var_bi
var_av = sigrshift var_as 5
var_hy = siglshift var_hu 15
var_gt = signot var_gs
var_fv = sigand var_fs var_fu
var_dk = sigand var_dh var_dj
var_cc = sigand var_bz var_cb
var_er = sigrshift var_dy 1
var_he = sigor var_hc var_hd
var_ga = sigor var_fo var_fz
var_u = sigor var_t var_s
var_d = sigrshift var_b 2
var_jz = signot var_jy
var_ia = sigrshift var_hz 2
var_kx = sigand var_kk var_kv
var_gd = sigand var_ga var_gc
var_gf = siglshift var_fl 1
var_ca = sigand var_bn var_by
var_hs = signot var_hr
var_bt = signot var_bs
var_lh = sigrshift var_lf 3
var_ax = sigand var_au var_av
var_ge = sigand 1 var_gd
var_jt = sigor var_jr var_js
var_fz = sigand var_fw var_fy
var_ja = signot var_iz
var_t = siglshift var_c 1
var_eb = sigrshift var_dy 5
var_br = sigor var_bp var_bq
var_i = signot var_h
var_dt = sigand 1 var_ds
var_ae = sigand var_ab var_ad
var_bj = siglshift var_ap 1
var_bu = sigand var_br var_bt
var_cb = signot var_ca
var_em = signot var_el
var_w = siglshift var_s 15
var_gr = sigor var_gk var_gq
var_fi = sigand var_ff var_fh
var_kj = siglshift var_kf 15
var_fx = sigand var_fp var_fv
var_lj = sigor var_lh var_li
var_bp = sigrshift var_bn 3
var_kb = sigor var_jp var_ka
var_lx = sigor var_lw var_lv
var_jb = sigand var_iy var_ja
var_ek = sigor var_dy var_ej
var_bi = sigand 1 var_bh
var_ku = signot var_kt
var_ap = sigor var_ao var_an
var_ii = sigand var_ia var_ig
var_ez = signot var_ey
var_cg = sigrshift var_bn 1
var_fl = sigor var_fk var_fj
var_cf = sigor var_ce var_cd
var_fc = sigand var_eu var_fa
var_kh = sigor var_kg var_kf
var_ju = sigand var_jr var_js
var_iw = sigrshift var_iu 3
var_di = sigand var_df var_dg
var_do = sigand var_dl var_dn
var_le = siglshift var_la 15
var_gh = sigrshift var_fo 1
var_gx = signot var_gw
var_gc = signot var_gb
var_jl = siglshift var_ir 1
var_ak = sigand var_x var_ai
var_hh = sigrshift var_he 5
var_lv = sigand 1 var_lu
var_fu = signot var_ft
var_gj = sigor var_gh var_gi
var_li = sigrshift var_lf 5
var_z = sigrshift var_x 3
var_e = sigrshift var_b 3
var_hf = sigrshift var_he 2
var_fy = signot var_fx
var_jw = sigand var_jt var_jv
var_hz = sigor var_hx var_hy
var_kc = sigand var_jp var_ka
var_fe = sigand var_fb var_fd
var_il = sigor var_hz var_ik
var_db = sigrshift var_ci 1
var_gb = sigand var_fo var_fz
var_ft = sigand var_fq var_fr
var_gk = sigrshift var_gj 2
var_ci = sigor var_cg var_ch
var_ch = siglshift var_cd 15
var_kg = siglshift var_jm 1
var_ik = sigand var_ih var_ij
var_fq = sigrshift var_fo 3
var_fr = sigrshift var_fo 5
var_fj = sigand 1 var_fi
var_la = sigand 1 var_kz
var_jh = sigand var_iu var_jf
var_ct = sigand var_cq var_cs
var_ep = siglshift var_dv 1
var_hm = sigor var_hf var_hl
var_kp = sigand var_km var_kn
var_dm = sigand var_de var_dk
var_dg = sigrshift var_dd 5
var_lp = signot var_lo
var_jv = signot var_ju
var_fh = signot var_fg
var_cp = sigand var_cm var_co
var_ed = sigand var_ea var_eb
var_df = sigrshift var_dd 3
var_gu = sigand var_gr var_gt
var_eq = sigor var_ep var_eo
var_cr = sigand var_cj var_cp
var_lr = sigor var_lf var_lq
var_ha = siglshift var_gg 1
var_eu = sigrshift var_et 2
var_ji = signot var_jh
var_en = sigand var_ek var_em
var_jo = siglshift var_jk 15
var_ih = sigor var_ia var_ig
var_gy = sigand var_gv var_gx
var_fg = sigand var_et var_fe
var_lk = sigand var_lh var_li
var_ip = sigand 1 var_io
var_ke = sigand var_kb var_kd
var_kn = sigrshift var_kk 5
var_ig = sigand var_id var_if
var_lt = signot var_ls
var_dy = sigor var_dw var_dx
var_dq = sigand var_dd var_do
var_ls = sigand var_lf var_lq
var_kd = signot var_kc
var_el = sigand var_dy var_ej
var_kf = sigand 1 var_ke
var_ff = sigor var_et var_fe
var_ic = sigrshift var_hz 5
var_dp = sigor var_dd var_do
var_cq = sigor var_cj var_cp
var_dr = signot var_dq
var_ld = sigrshift var_kk 1
var_jj = sigand var_jg var_ji
var_hq = sigor var_he var_hp
var_hl = sigand var_hi var_hk
var_ds = sigand var_dp var_dr
var_eh = sigand var_dz var_ef
var_ib = sigrshift var_hz 3
var_dd = sigor var_db var_dc
var_iq = siglshift var_hw 1
var_hr = sigand var_he var_hp
var_cs = signot var_cr
var_lo = sigand var_lg var_lm
var_hw = sigor var_hv var_hu
var_io = sigand var_il var_in
var_ei = signot var_eh
var_hd = siglshift var_gz 15
var_gs = sigand var_gk var_gq
var_eo = sigand 1 var_en
var_kq = signot var_kp
var_ew = sigrshift var_et 5
var_lm = sigand var_lj var_ll
var_hg = sigrshift var_he 3
var_ev = sigrshift var_et 3
var_bf = sigand var_as var_bd
var_cx = sigand var_cu var_cw
var_ka = sigand var_jx var_jz
var_o = sigor var_b var_n
var_bh = sigand var_be var_bg
var_hu = sigand 1 var_ht
var_gz = sigand 1 var_gy
var_ho = signot var_hn
var_cm = sigor var_ck var_cl
var_ef = sigand var_ec var_ee
var_lz = siglshift var_lv 15
var_kv = sigand var_ks var_ku
var_if = signot var_ie
var_hn = sigand var_hf var_hl
var_s = sigand 1 var_r
var_ie = sigand var_ib var_ic
var_ht = sigand var_hq var_hs
var_ag = sigand var_y var_ae
var_ee = signot var_ed
var_bm = siglshift var_bi 15
var_dz = sigrshift var_dy 2
var_cj = sigrshift var_ci 2
var_bg = signot var_bf
var_in = signot var_im
var_ex = sigor var_ev var_ew
var_id = sigor var_ib var_ic
var_bo = sigrshift var_bn 2
var_de = sigrshift var_dd 2
var_bn = sigor var_bl var_bm
var_bl = sigrshift var_as 1
var_ec = sigor var_ea var_eb
var_lq = sigand var_ln var_lp
var_km = sigrshift var_kk 3
var_iu = sigor var_is var_it
var_iv = sigrshift var_iu 2
var_be = sigor var_as var_bd
var_it = siglshift var_ip 15
var_iy = sigor var_iw var_ix
var_kl = sigrshift var_kk 2
var_bc = signot var_bb
var_cl = sigrshift var_ci 5
var_ma = sigor var_ly var_lz
var_ac = sigand var_z var_aa
var_jn = sigrshift var_iu 1
var_dc = siglshift var_cy 15
var_cz = siglshift var_cf 1
var_au = sigrshift var_as 3
var_da = sigor var_cz var_cy
var_kz = sigand var_kw var_ky
var_a = var_lx
var_iz = sigand var_iw var_ix
var_lu = sigand var_lr var_lt
var_js = sigrshift var_jp 5
var_az = sigand var_aw var_ay
var_jf = sigand var_jc var_je
var_lc = sigor var_lb var_la
var_co = signot var_cn
var_lb = siglshift var_kh 1
var_jk = sigand 1 var_jj
var_af = sigor var_y var_ae
var_cn = sigand var_ck var_cl
var_kw = sigor var_kk var_kv
var_cw = signot var_cv
var_kt = sigand var_kl var_kr
var_jg = sigor var_iu var_jf
var_bb = sigand var_at var_az
var_jq = sigrshift var_jp 2
var_jd = sigand var_iv var_jb
var_jp = sigor var_jn var_jo
var_aj = sigor var_x var_ai
var_bd = sigand var_ba var_bc
var_jm = sigor var_jl var_jk
var_v = sigrshift var_b 1
var_r = sigand var_o var_q
var_q = signot var_p
var_n = sigand var_k var_m
var_at = sigrshift var_as 2
